doctype = 'article'
class_options = [ '12pt' ]

bibstyle = 'plain'
styles = ['palatino-header']

macros = [
    'general',
    'typesetting',
    'doublespacing',
    'fractals',
    'refs_ams',
    'theorem_ams'
]

constants = [
    'papername',
    'journal'
]

[geometry]
bottom = '3cm'
left = '2.5cm'
right = '2.5cm'
top = '2.5cm'
