doctype = 'letter'
class_options = [ '12pt' ]

bibstyle = 'plain'
style = 'palatino'

macros = [
    'general',
    'typesetting'
]

constants = [
    'recipientaddress'
]

[geometry]
bottom = '2cm'
left = '3cm'
right = '3cm'
top = '2cm'
