doctype = 'article'
class_options = [ '12pt' ]

bibstyle = 'plain'
format = 'palatino'

macros = [
    'general',
    'typesetting',
    'refs_ams',
    'theorem_ams'
]

constants = [
    'titlename'
]

[geometry]
bottom = '3cm'
left = '2.5cm'
right = '2.5cm'
top = '2.5cm'
