project_macro_file: project-macros

classinfo_file: ".classinfo"
bibinfo_file: ".bibinfo"

macro_prefix : macros
formatting_prefix : format
citation_prefix: citations
prefix_separator: '-'

export_suffixes:
  - .tex
  - .bib
  - .pdf
  - .sty
