project_macro_file : project-macros
project_macro_file_contents: "% project-specific macros\n"

macro_prefix : macros
formatting_prefix : format
citation_prefix: citations

default_bibstyle: plain
export_suffixes:
  - .tex
  - .bib
  - .pdf
  - .sty
