[user]
name = 'John Doe'
initials = 'JD'
address = '123 Example Ave, City, ON'
email = 'your@email.com'
institution = 'Nonexistent University'
website = 'https://your.domain'
grant = 'Prestigious Funder Grant 123456'

[github]
username = 'gh_username'
repo_api_token = '/path/to/retrival/command'

[github.archive]
repo = 'reponame'
folder = 'path/to/export/folder'
branch = 'main'

[render]
arxiv_autotex = [
    'nohypertext',
    'nostamp'
]

[process]
# always called with -pdf -interaction=nonstopmode so that it can be run without user input
latexmk_compile_options = [
    '-silent',
    '-Werror',
    '-file-line-error'
]

# files to ignore when exporting source files, and in .gitignore
ignore_patterns = [
    '*.aux',
    '*.bak',
    '*.bbl',
    '*.bcf',
    '*.blg',
    '*.brf',
    '*.fdb_latexmk',
    '*.fls',
    '*.log',
    '*.mtc',
    '*.out',
    '*.pdf',
    '*.pgs',
    '*.run.xml',
    '*.synctex.gz',
    '*.tar*',
    '*.thm',
    '*.toc',
    '*.zip',
    '.DS_Store',
    '.git',
    'archive*',
    'tmp'
]
