# naming conventions used within the .texproject folder
classinfo_file: "classinfo"
bibinfo_file: "bibinfo"
project_data_folder: ".texproject"
default_tex_name: "main"
project_macro_file: "project-macros"
macro_prefix: "macro"
format_prefix: "format"
citation_prefix: "citation"
prefix_separator: '-'

arxiv_autotex:
  - nohypertext
  - nostamp

# text substituted for fields which require user input
replace_text: 'REPLACE'

# default compression algorithm when exporting
default_compression: 'zip'

# latex compliation command
latex_compile_command: 'latexmk -pdf -file-line-error -interaction=nonstopmode -Werror'

# files to ignore when exporting and in .gitignore
ignore_patterns:
  - "*.aux"
  - "*.bak"
  - "*.bbl"
  - "*.bcf"
  - "*.blg"
  - "*.brf"
  - "*.fdb_latexmk"
  - "*.fls"
  - "*.log"
  - "*.mtc"
  - "*.out"
  - "*.pdf"
  - "*.pgs"
  - "*.run.xml"
  - "*.synctex.gz"
  - "*.tar*"
  - "*.thm"
  - "*.toc"
  - "*.zip"
  - ".DS_Store"
  - ".git"
  - "archive*"
  - "tmp"
