# project filename defaults
classinfo_file: "classinfo"
bibinfo_file: "bibinfo"
project_data_folder: ".texproject"
default_tex_name: "main"
project_macro_file: "project-macros"
macro_prefix: "macro"
format_prefix: "format"
citation_prefix: "citation"
prefix_separator: '-'
replace_text: 'REPLACE'

# default settings for CLI
default_compression: 'zip'
latex_compile_command: 'latexmk -pdf -silent -outdir=.texproject/aux'

# ignore when exporting and in .gitignore
ignore_patterns:
  - "*.aux"
  - "*.bcf"
  - "*.blg"
  - "*.pgs"
  - "*.bak"
  - "*.mtc"
  - "*.fdb_latexmk"
  - "*.fls"
  - "*.log"
  - "*.out"
  - "*.synctex.gz"
  - "*.toc"
  - "*.tar*"
  - "*.zip"
  - "tmp*"
