doctype = 'amsart'
class_options = [ '12pt' ]

bibstyle = 'amsplain'
styles = ['palatino']

macros = [
    'typesetting',
    'general',
    'refs_ams',
    'theorem_ams'
]

constants = [
    'titlename',
    'shorttitlename',
    'docclasses',
    'dockeywords'
]

[geometry]
left = '3cm'
right = '3cm'
top = '3.8cm'
